[SNAPSHOT]
snapshot_interval_minutes = 10
compress_state = True

[MASKING]
masking = [
    # 1. Mask Timestamps (2026-07-28 10:00:01,123)
    {"regex_pattern": "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2},\\d{3}", "mask_with": "ID_TIME"},

    # 2. Mask Block IDs (blk_123456789) - HIGH CARDINALITY
    {"regex_pattern": "\\bblk_-?\\d+\\b", "mask_with": "ID_BLOCK"},

    # 3. Mask Block Pool IDs (BP-12345-10.0.0.1-12345)
    {"regex_pattern": "\\bBP-[\\d\\.-]+(?=:|\\b)", "mask_with": "ID_POOL"},

    # 4. Mask IP Addresses and Ports
    {"regex_pattern": "\\b\\d{1,3}(\\.\\d{1,3}){3}\\b", "mask_with": "ID_IP"},

    # 5. Mask File/Folder Paths
    {"regex_pattern": "(?<=/)[\\w\\./-]{4,}", "mask_with": "ID_PATH"},

    # 6. Mask Standalone Numbers (Sizes, packet IDs, sequence numbers)
    {"regex_pattern": "\\b\\d+\\b", "mask_with": "ID_VAL"},
    
    {"regex_pattern": "(?<=[a-zA-Z])\\d+|\\d+(?=[a-zA-Z])", "mask_with": "ID_VAL"}
    ]
[DRAIN]
sim_th = 1
depth = 12
max_children = 1000
max_clusters = 5000
extra_delimiters = [' ', ',', ':', '/', '[', ']', '(', ')', '-', '=']