[SNAPSHOT]
snapshot_interval_minutes = 10
compress_state = True

[MASKING]
masking = [
    # 1. Mask Timestamps
    {"regex_pattern": "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3} \\w+", "mask_with": "ID_TIME"},
    
    # 2. Mask PIDs
    {"regex_pattern": "(?<=\\[)\\d+(?=\\])", "mask_with": "ID_PID"},

    # 3. Mask IP Addresses
    {"regex_pattern": "\\b\\d{1,3}(\\.\\d{1,3}){3}\\b", "mask_with": "ID_IP"},

    # 4. Mask Standalone Numbers (IDs, Limits, Offsets)
    # This will catch '101', '5000', '5001' etc.
    {"regex_pattern": "\\b\\d+\\b", "mask_with": "ID_VAL"},

    # 5. Mask Hex/OIDs
    {"regex_pattern": "\\b0x[a-fA-F0-9]+\\b|\\b\\d{5,}\\b", "mask_with": "ID_HEX"},
    # 6. Mask Emails or anything inside parentheses that isn't a simple number
    {"regex_pattern": "(?<=\\()([^)]+)(?=\\))", "mask_with": "ID_VAR"}
    ]

[DRAIN]
sim_th = 1
depth = 15
extra_delimiters = [' ', '"', '[', ']', '(', ')', ',', ';', '=', "'"]
max_children = 1000
max_clusters = 5000